### ISSUE TITLE
[general] Remove references / documentation with reloaded

### ISSUE THREAD

**Issue by tprouvot** [dufoli/Salesforce-Inspector-Advanced#14]
**Is your feature request related to a problem? Please describe.**
Since this project can be mistaken with reloaded it would be great to have a clear distinction between those two.

**Describe the solution you'd like**

- [x] Update README.md to remove references from extension `hpijlohoihegkfehhibggnkbjhoemldh`
- [x] Update extension's icon and logo
- [x] Remove references to reloaded connected app
- [x] Update CHANGES.md to list only new features from 'advanced' 
- [x] Update documentation pages (mkdocs material) `./docs` folder to remove all ref from reloaded

Thank you.

**Comment by dufoli** [comment]
@tprouvot 
I have change to todo list:
- for icon, I am not a graphist and it is cover by mit so I will change it when I have time or when I received a PR for that.
- I do not get what you mean by reference to reloaded connected app.
- I have keep the changes.md to show the hard work done on the project done by everybody and not only me... Are you sure about  that ?
- I can remove ref to reloaded on docs but same than on changes, I do that to keep reference to commiter and not confuse people by thinking that I have done all by myself.

**Comment by tprouvot** [comment]
@dufoli 

- Our connected app is configured [here](https://github.com/dufoli/Salesforce-Inspector-Advanced/blob/7259e75080b8284aa724e0f756ff01afba61e87c/addon/popup.js#L227), since it contains a callback url with reloaded extension id, it does not work with advanced.

- If you wan to keep the work done in reloaded, please mention it in the version header, otherwise I prefer you to remove it from yours. ie `Version 1.23 (Salesforce Inspector reloaded)`

- Same logical for documentation, ff you want to keep the work done in reloaded, please mention it wherever it is used

- For icon here's an example, I'm not a designer either but it can help to differentiate the extensions

<img width="540" alt="image" src="https://github.com/dufoli/Salesforce-Inspector-Advanced/assets/35368290/35aa1807-d050-4ff1-a2df-60a2371f27e6">
 
[SFA.pptx](https://github.com/dufoli/Salesforce-Inspector-Advanced/files/14691571/SFA.pptx)

**Comment by dufoli** [comment]
Bon j'ai fait un icon rapidement avec inkscape ca ira pour le moment...
