### ISSUE TITLE
Inline editing in Data Export not working

### ISSUE THREAD

**Issue by bonzi-123** [dufoli/Salesforce-Inspector-Advanced#158]
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://dufoli.github.io/Salesforce-Inspector-Advanced/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
When attempting to change the current value using inline edit, the current value cannot be deleted from the text editor, and when you try to write something, only the first letter of what you are trying to write appears, after having clicked out of the cell you are editing.

**To Reproduce**
1. Go to Data Export
2. Query for example editable fields in Contact (FirstName,LastName)
3. Attempt to inline edit a field

**Expected behavior**
To be able to change the value of the cell one wants to edit.

**Screenshots**
I attach a video of the issue.
https://github.com/user-attachments/assets/5d789725-dae7-4819-821c-bd024ebc5235

**Desktop (please complete the following information):**
 - OS: Mac OS 14.5 (23F79)
 - Browser: Chrome Version 127.0.6533.100 (Official Build) (x86_64)
 - Version 1.28.3

**Additional context**

**Comment by dufoli** [comment]
it is fiexed on main branch with https://github.com/dufoli/Salesforce-Inspector-Advanced/commit/3c7858bf7401930421334401d0920142adee9b2e

**Comment by bonzi-123** [comment]
Hello,

When you say that it's in the main branch, do you mean that I can download the fix and have it locally? Do you know when it will be available inside an official version of Salesforce Inspector Advanced?

Thanks
