### ISSUE TITLE
Saved Queries Title not appearing in "Saved Queries" List

### ISSUE THREAD

**Issue by bonzi-123** [dufoli/Salesforce-Inspector-Advanced#159]
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://dufoli.github.io/Salesforce-Inspector-Advanced/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
Saved Queries Title not appearing in "Saved Queries" List

**To Reproduce**
1. Go to Data Export
2. Click on "Saved Queries" to see the Saved Queries list

**Expected behavior**
To see the title of the query + the SOQL

**Screenshots**
<img width="798" alt="Screenshot 2024-08-11 at 09 19 16" src="https://github.com/user-attachments/assets/ec93ba15-fbdb-4487-955c-cd231e38519c">

**Desktop (please complete the following information):**
 - OS: Mac OS 14.5 (23F79)
 - Browser: Chrome Version 127.0.6533.100 (Official Build) (x86_64)
 - Version 1.28.3

**Additional context**

**Comment by dufoli** [comment]
Hmm strange, it appear on my side, not as an option but on top:
![image](https://github.com/user-attachments/assets/f28a9b19-07db-4473-bc01-7ff2aff2390e)
Anyway, do we really need this, you can click out if you do not want to select a value.
If I add it, we will need to handle that if we select it nothing happened.

**Comment by bonzi-123** [comment]
Hello, I'm referring to the title that you give the Query when you save it, not the "Saved Queries" button. For example, you save "SELECT Id, Status FROM AsyncApexJob" and you give it the title "Async Query". That title should appear just before the Query, like:

Async Query - SELECT Id, Status FROM AsyncApexJob

Hope this is more clear.

Thanks!

**Comment by bonzi-123** [comment]
Here is a screenshot of what I'm referring to. If the label is not being shown in this menu, then adding a label to a Query doesn't make sense.

<img width="775" alt="Screenshot 2024-08-19 at 20 09 10" src="https://github.com/user-attachments/assets/f93bda32-e559-42bf-994b-7da803fe9e32">

Thanks
