### ISSUE TITLE
When opening the extension sidebar, extra click is needed to activate keyboard shortcuts 

### ISSUE THREAD

**Issue by bonzi-123** [dufoli/Salesforce-Inspector-Advanced#160]
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://dufoli.github.io/Salesforce-Inspector-Advanced/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
When opening the extension sidebar, extra click is needed to activate keyboard shortcuts

**To Reproduce**
1. Click on side arrow to open extension
2. Click "e" to go to "Export" - this will not open "Export", you need an extra click to focus inside the extension in order for keyboard shortcuts to work. 

**Expected behavior**
To be able to use keyboard shortcuts right after opening the extension sidebar

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 14.5 (23F79)
 - Browser: Chrome Version 127.0.6533.100 (Official Build) (x86_64)
 - Version 1.28.3

**Additional context**

**Comment by dufoli** [comment]
Hello, thanks for the feedback.
I discover this issue too and I try to fix it with chrome extension shortcut. it can be configure under extension Settings :
By default ctrl + Shift + E open the export.
![image](https://github.com/user-attachments/assets/6b070ad3-f183-493d-b2d3-399d97d6e0b8)
I am thinking to add a system to forward from shortcut because we are limited with extension shortcut to only 4 shortcuts.

**Comment by bonzi-123** [comment]
I think what you mention can be added, but I still believe that when you open the Extension pop-up, it should be auto-focused so that pressing a letter you can get to Export, Import or Shortcuts. Both things are not incompatible - I myself prefer to have a universal shortcut for Salesforce Inspector Advanced and then click an individual letter to go to Export, Import, etc.

This was an existing feature in Salesforce Inspector Reloaded, there is no need for the extra click there.

Thanks

**Comment by dufoli** [comment]
it has bn fixed. I will release very soon with this fix.
