### ISSUE TITLE
Access Token Expired, Generate New Token

### ISSUE THREAD

**Issue by mostafaghonem** [dufoli/Salesforce-Inspector-Advanced#165]
I have an issue on a specific org, I get this message "Access Token Expired Generate New Token", I tried to clear the cache and the session, but it is not working as well.
When clicking Generate New Token, I get a redirect error.

<img width="333" alt="image" src="https://github.com/user-attachments/assets/e07cdf56-8d6f-47f0-bc41-e507581e6562">

**Comment by idletech2** [comment]
Hi, I'm still receiving this error on a regular basis. every time i go to the connected apps i don't see anything for inspector :( and i get a redirect error as well

![Image](https://github.com/user-attachments/assets/2380b244-c9b0-4db7-9f82-4fd1cc98a4a3)

**Comment by dufoli** [comment]
indeed SFI and SFI reloaded let the web service failed. I maybe will do so because it is anoying. I have no more this issue on my side but I know it can happen sometimes.

**Comment by dufoli** [comment]
Anyway, I will need some times to work on few bugs and produce a new version with some features too.
