### ISSUE TITLE
ORDER BY clause in SOQL not working properly

### ISSUE THREAD

**Issue by ShrodingersKat** [dufoli/Salesforce-Inspector-Advanced#184]
**Make sure to read the troubleshooting section before creating an issue**

- [x ] I've read the [common issues](https://dufoli.github.io/Salesforce-Inspector-Advanced/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
When I export data using ORDER BY in the SOQL, there's some ordering happening but I can't understand how as the order is wrong

**To Reproduce**
1. Go to Data Export
2. Enter a query that tries to order on picklist values (mine had more than one word but I'm not sure it matters)
3. Check ordering of column

**Expected behavior**
I expected to see the records ordered consistently by that column. That was not the case. Screenshots will be added

**Screenshots**
![Screenshot 2024-10-23 182517](https://github.com/user-attachments/assets/05561dfa-ca8a-45bd-a317-74c297072e42)
![Screenshot 2024-10-23 182455](https://github.com/user-attachments/assets/bfde5902-b971-4166-958b-55a18eda08b6)
![Screenshot 2024-10-23 182430](https://github.com/user-attachments/assets/451ef2c7-1cfd-41a8-84b9-83d713ff75d6)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 1.29.1

**Additional context**

**Comment by dufoli** [comment]
Hello, Thanks for reporting this issue. It is strange behaviour but I need to check if it is related to saleforce query api or inspector...
Can you try to execture the same query on developper console > query tab ?

**Comment by ShrodingersKat** [comment]
Yes, good call. Definitely something weird going on. This is from the Developer Console.

![image](https://github.com/user-attachments/assets/574cd56e-92b8-4121-996a-961516c0ce7b)

**Comment by ShrodingersKat** [comment]
Guess that's that. Sorry for the nuisance. Should have checked first this. I just didn't think that as a possibility. Very odd behaviour.

**Comment by ShrodingersKat** [comment]
Thanks.

**Comment by dufoli** [comment]
@ShrodingersKat Great ! sad that it come from core ;-(
