### ISSUE TITLE
Publish firefox and edge store extension

### ISSUE THREAD

**Issue by dufoli** [dufoli/Salesforce-Inspector-Advanced#69]
- [x] publish extension on firefox store
- [ ] publish extension on edge microsoft store
- [x] update doc to point to store

edg store support the chrome store... So skip it for moment.
https://learn.microsoft.com/fr-fr/windows/uwp/monetize/create-an-add-on-submission

**Comment by 0cv** [comment]
I gave it a try in Firefox, but I think there is an error and the extension doesn't load with a problem in links.js `SyntaxError: export declarations may only appear at top level of a module`

<img width="1440" alt="image" src="https://github.com/dufoli/Salesforce-Inspector-Advanced/assets/1253866/28321caf-e5bd-4ec9-9fd6-76f359139ee5">

**Comment by dufoli** [comment]
@0cv I have fixed an issue with the original manifest.json to rmove links.js from it.

**Comment by dufoli** [comment]
@0cv can you retry with last version?

**Comment by 0cv** [comment]
> @0cv can you retry with last version?

Did that work for you? It doesn't for me (the links error has disappeared, but the extension isn't showing up)

**Comment by dufoli** [comment]
@0cv now yes. Indeed the firefox build do not worked at all with script on reloaded. There was an error on manifest and a bug introduce by mac testing on reloaded that I need to remove. Anyway now it is working.
